enquete_wps/src/enquete/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('votacoes/', include('votacoes.urls')),
    path('admin/', admin.site.urls),
]

enquete_wps/src/votacoes/urls.py
from django.urls import path

from . import views

app_name = 'votacoes'

urlpatterns = [
    # ex: /votaces/
    path('', views.IndexView.as_view(), name='index'),
     # ex: /votaces/5/
    path ('<int:pk>/', views.DetalhesView.as_view, name='detalhes'),
    # ex: /votaces/5/resultados/
    path('<int:pk>/resultados', views.ResultadosView.as_view, name='resultados'),
    # ex: /votaces/5/votar
    #path('int:questao_id>/votar/', views.votar, name='votar'),
]

enquete_wps/src/votacoes/models.py
from django.db import models
from django.utils import timezone

class Questao (models.Model):
    questao_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Data de Publicação')

    def __str__(self):
        return self.questao_text
    
    def foi_publicado_recentemente(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Opcao (models.Model):
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    opcao_text = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.opcao_text
# Create your models here.

enquete_wps/src/votacoes/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, Http404, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Questao, Opcao

class IndexView(generic.ListView):
    template_name = 'votacoes/index.html'
    context_object_name = 'lista_ultimas_questoes'

    def get_queryset(self):
        return Questao.objects.order_by('-pub_date')[:5]

class DetalhesView(generic.DetailView):
    model = Questao
    template_name = 'votacoes/detalhes.html'

class ResultadosView(generic.DetailView):
    model = Questao
    template_name = 'votacoes/resultados.html'

# def index (request):
 #   list_ultimas_questoes = Questao.objects.order_by('-pub_date')[:5]
  #  context = { 'lista_ultimas_questoes': lista_ultimas_questoes }
   # return render(request, 'votacoes/index.html', context)

#def detalhes (request, questao_id):
#    questao = get_object_or_404(Questao, pk=questao_id)
#    return render(request, 'votacoes/detalhes.html', {'questao': questao})

#def resultados(request, questao_id):
#    questao =  get_object_or_404(Questao, pk=questao_id)
#    return render(request, 'votacoes/resultados.html', {'questao': questao})

#def votar(request, questao_id):
#    questao = get_object_or_404(Questao, pk=questao_id)
#    try:
#        op_selecionada = questao.opcao_set.get(pk=request.POSt['opcao'])
#    except (KeyError, Opcao.DoesNotExist):
#        return render(request, 'votacoes/detalhes.html', {
#            'questao': questao,
#            'msg_erro': 'Você não selecionou uma opção.',
 #       })
  #  else:
   #     op_selecionada.votos += 1
    #    op_selecionada.save()
     #   return HttpResponseRedirect(reverse('votacoes:resultados',
    #                                args=(questao_id)))

enquete_wps/src/votacoes/templates/votacoes/detalhes.html
<h1>{{ questao.questao_text }}</h1>
{% if msg_erro %}<p><strong>{{ msg_erro }}</strong></p>{% endif %}

<form action="{% url 'votacoes:votar' questao.id %}" method="POST">
{% csrf_token %}
{% for opcao inquestao.opcao_set.all %}
    <input type="radio" name="opcao" id="opcao{{ forloop.counter }}" value="{{ opcao.id }}">
    <label for="opcao{{ forloop.counter }}">{{ opcao.opcao_text }}</label><br>
{% endfor %}
<input type="submit" value="Votar">
</form>

enquete_wps/src/votacoes/templates/votacoes/index.html
{% if lista_ultimas_questoes %}
    <ul>
        {% for questao in lista_ultimas_questoes %}
            <li><a href="{% url 'votacoes:detalhes' question.id %}/">{{ questao.questao_text }}</a></li>
        {% enfor %}
        </ul>
{% else %}
    <p>Não existem votações disponíveis.</p>
{% endif %}

enquete_wps/src/votacoes/templates/votacoes/resultados.html
<h1>{{ questao.questao_text }}</h1>

<ul>
    {% for opcao in questao.opcao_set.all %}
        <li>{{ opcao.opcao_text }} -- {{ opcao.votos }}</li>
    {% endfor %}
</ul>

<a href="{% url 'votacoes:detalhes' questao.id %} ">Votar Novamente?</a>